export const COUNTRIES = [
  {
    name: 'Afghanistan',
    dialCode: '+93',
    code: 'AF',
    image: 'flag-af',
    latitude: 33,
    longitude: 65,
    id: 3,
  },
  {
    name: 'Albania',
    dialCode: '+355',
    code: 'AL',
    image: 'flag-al',
    latitude: 41,
    longitude: 20,
    id: 6,
  },
  {
    name: 'Algeria',
    dialCode: '+213',
    code: 'DZ',
    image: 'flag-dz',
    latitude: 28,
    longitude: 3,
    id: 59,
  },
  {
    name: 'AmericanSamoa',
    dialCode: '+1 684',
    code: 'AS',
    image: 'flag-as',
    latitude: -14.3333,
    longitude: -170,
    id: 12,
  },
  {
    name: 'Andorra',
    dialCode: '+376',
    code: 'AD',
    image: 'flag-ad',
    latitude: 42.5,
    longitude: 1.6,
    id: 1,
  },
  {
    name: 'Angola',
    dialCode: '+244',
    code: 'AO',
    image: 'flag-ao',
    latitude: -12.5,
    longitude: 18.5,
    id: 9,
  },
  {
    name: 'Anguilla',
    dialCode: '+1 264',
    code: 'AI',
    image: 'flag-ai',
    latitude: 18.25,
    longitude: -63.1667,
    id: 5,
  },
  {
    name: 'Antarctica',
    dialCode: '+672',
    code: 'AQ',
    image: 'flag-aq',
    latitude: -90,
    longitude: '0',
    id: 10,
  },
  {
    name: 'Antigua and Barbuda',
    dialCode: '+1268',
    code: 'AG',
    image: 'flag-ag',
    latitude: 17.05,
    longitude: -61.8,
    id: 4,
  },
  {
    name: 'Argentina',
    dialCode: '+54',
    code: 'AR',
    image: 'flag-ar',
    latitude: -34,
    longitude: -64,
    id: 11,
  },
  {
    name: 'Armenia',
    dialCode: '+374',
    code: 'AM',
    image: 'flag-am',
    latitude: 40,
    longitude: 45,
    id: 7,
  },
  {
    name: 'Aruba',
    dialCode: '+297',
    code: 'AW',
    image: 'flag-aw',
    latitude: 12.5,
    longitude: -69.9667,
    id: 15,
  },
  {
    name: 'Australia',
    dialCode: '+61',
    code: 'AU',
    image: 'flag-au',
    latitude: -27,
    longitude: 133,
    id: 14,
  },
  {
    name: 'Austria',
    dialCode: '+43',
    code: 'AT',
    image: 'flag-at',
    latitude: 47.3333,
    longitude: 13.3333,
    id: 13,
  },
  {
    name: 'Azerbaijan',
    dialCode: '+994',
    code: 'AZ',
    image: 'flag-az',
    latitude: 40.5,
    longitude: 47.5,
    id: 16,
  },
  {
    name: 'Bahamas',
    dialCode: '+1 242',
    code: 'BS',
    image: 'flag-bs',
    latitude: 24.25,
    longitude: -76,
    id: 31,
  },
  {
    name: 'Bahrain',
    dialCode: '+973',
    code: 'BH',
    image: 'flag-bh',
    latitude: 26,
    longitude: 50.55,
    id: 23,
  },
  {
    name: 'Bangladesh',
    dialCode: '+880',
    code: 'BD',
    image: 'flag-bd',
    latitude: 24,
    longitude: 90,
    id: 19,
  },
  {
    name: 'Barbados',
    dialCode: '+1 246',
    code: 'BB',
    image: 'flag-bb',
    latitude: 13.1667,
    longitude: -59.5333,
    id: 18,
  },
  {
    name: 'Belarus',
    dialCode: '+375',
    code: 'BY',
    image: 'flag-by',
    latitude: 53,
    longitude: 28,
    id: 34,
  },
  {
    name: 'Belgium',
    dialCode: '+32',
    code: 'BE',
    image: 'flag-be',
    latitude: 50.8333,
    longitude: 4,
    id: 20,
  },
  {
    name: 'Belize',
    dialCode: '+501',
    code: 'BZ',
    image: 'flag-bz',
    latitude: 17.25,
    longitude: -88.75,
    id: 35,
  },
  {
    name: 'Benin',
    dialCode: '+229',
    code: 'BJ',
    image: 'flag-bj',
    latitude: 9.5,
    longitude: 2.25,
    id: 25,
  },
  {
    name: 'Bermuda',
    dialCode: '+1 441',
    code: 'BM',
    image: 'flag-bm',
    latitude: 32.3333,
    longitude: -64.75,
    id: 27,
  },
  {
    name: 'Bhutan',
    dialCode: '+975',
    code: 'BT',
    image: 'flag-bt',
    latitude: 27.5,
    longitude: 90.5,
    id: 32,
  },
  {
    name: 'Bolivia, Plurinational State of Bolivia',
    dialCode: '+591',
    code: 'BO',
    image: 'flag-bo',
    latitude: -17,
    longitude: -65,
    id: 29,
  },
  {
    name: 'Bosnia and Herzegovina',
    dialCode: '+387',
    code: 'BA',
    image: 'flag-ba',
    latitude: 44,
    longitude: 18,
    id: 17,
  },
  {
    name: 'Botswana',
    dialCode: '+267',
    code: 'BW',
    image: 'flag-bw',
    latitude: -22,
    longitude: 24,
    id: 33,
  },
  {
    name: 'Bouvet Island',
    dialCode: '+55',
    code: 'BV',
    image: 'flag-bv',
    latitude: -54.4333,
    longitude: 3.4,
  },
  {
    name: 'Brazil',
    dialCode: '+55',
    code: 'BR',
    image: 'flag-br',
    latitude: -10,
    longitude: -55,
    id: 30,
  },
  {
    name: 'British Indian Ocean Territory',
    dialCode: '+246',
    code: 'IO',
    image: 'flag-io',
    latitude: -6,
    longitude: 71.5,
  },
  {
    name: 'Brunei Darussalam',
    dialCode: '+673',
    code: 'BN',
    image: 'flag-bn',
    latitude: 4.5,
    longitude: 114.6667,
    id: 28,
  },
  {
    name: 'Bulgaria',
    dialCode: '+359',
    code: 'BG',
    image: 'flag-bg',
    latitude: 43,
    longitude: 25,
    id: 22,
  },
  {
    name: 'Burkina Faso',
    dialCode: '+226',
    code: 'BF',
    image: 'flag-bf',
    latitude: 13,
    longitude: -2,
    id: 21,
  },
  {
    name: 'Burundi',
    dialCode: '+257',
    code: 'BI',
    image: 'flag-bi',
    latitude: -3.5,
    longitude: 30,
    id: 24,
  },
  {
    name: 'Cambodia',
    dialCode: '+855',
    code: 'KH',
    image: 'flag-kh',
    latitude: 13,
    longitude: 105,
    id: 106,
  },
  {
    name: 'Cameroon',
    dialCode: '+237',
    code: 'CM',
    image: 'flag-cm',
    latitude: 6,
    longitude: 12,
    id: 45,
  },
  {
    name: 'Canada',
    dialCode: '+1',
    code: 'CA',
    image: 'flag-ca',
    latitude: 60,
    longitude: -95,
    id: 36,
  },
  {
    name: 'Cape Verde',
    dialCode: '+238',
    code: 'CV',
    image: 'flag-cv',
    latitude: 16,
    longitude: -24,
    id: 50,
  },
  {
    name: 'Cayman Islands',
    dialCode: '+1345',
    code: 'KY',
    image: 'flag-ky',
    latitude: 19.5,
    longitude: -80.5,
    id: 113,
  },
  {
    name: 'Central African Republic',
    dialCode: '+236',
    code: 'CF',
    image: 'flag-cf',
    latitude: 7,
    longitude: 21,
    id: 39,
  },
  {
    name: 'Chad',
    dialCode: '+235',
    code: 'TD',
    image: 'flag-td',
    latitude: 15,
    longitude: 19,
    id: 197,
  },
  {
    name: 'Chile',
    dialCode: '+56',
    code: 'CL',
    image: 'flag-cl',
    latitude: -30,
    longitude: -71,
    id: 44,
  },
  {
    name: 'China',
    dialCode: '+86',
    code: 'CN',
    image: 'flag-cn',
    latitude: 35,
    longitude: 105,
    id: 46,
  },
  {
    name: 'Christmas Island',
    dialCode: '+61',
    code: 'CX',
    image: 'flag-cx',
    latitude: -10.5,
    longitude: 105.6667,
    id: 51,
  },
  {
    name: 'Cocos (Keeling) Islands',
    dialCode: '+61',
    code: 'CC',
    image: 'flag-cc',
    latitude: -12.5,
    longitude: 96.8333,
    id: 37,
  },
  {
    name: 'Colombia',
    dialCode: '+57',
    code: 'CO',
    image: 'flag-co',
    latitude: 4,
    longitude: -72,
    id: 47,
  },
  {
    name: 'Comoros',
    dialCode: '+269',
    code: 'KM',
    image: 'flag-km',
    latitude: -12.1667,
    longitude: 44.25,
    id: 108,
  },
  {
    name: 'Congo',
    dialCode: '+242',
    code: 'CG',
    image: 'flag-cg',
    latitude: -1,
    longitude: 15,
    id: 40,
  },
  {
    name: 'Congo, The Democratic Republic of the',
    dialCode: '+243',
    code: 'CD',
    image: 'flag-cd',
    latitude: '0',
    longitude: 25,
    id: 38,
  },
  {
    name: 'Cook Islands',
    dialCode: '+682',
    code: 'CK',
    image: 'flag-ck',
    latitude: -21.2333,
    longitude: -159.7667,
    id: 43,
  },
  {
    name: 'Costa Rica',
    dialCode: '+506',
    code: 'CR',
    image: 'flag-cr',
    latitude: 10,
    longitude: -84,
    id: 48,
  },
  {
    name: "Cote d'Ivoire",
    dialCode: '+225',
    code: 'CI',
    image: 'flag-ci',
    latitude: 8,
    longitude: -5,
    id: 42,
  },
  {
    name: 'Croatia',
    dialCode: '+385',
    code: 'HR',
    image: 'flag-hr',
    latitude: 45.1667,
    longitude: 15.5,
    id: 89,
  },
  {
    name: 'Cuba',
    dialCode: '+53',
    code: 'CU',
    image: 'flag-cu',
    latitude: 21.5,
    longitude: -80,
    id: 49,
  },
  {
    name: 'Cyprus',
    dialCode: '+357',
    code: 'CY',
    image: 'flag-cy',
    latitude: 35,
    longitude: 33,
    id: 52,
  },
  {
    name: 'Czech Republic',
    dialCode: '+420',
    code: 'CZ',
    image: 'flag-cz',
    latitude: 49.75,
    longitude: 15.5,
    id: 53,
  },
  {
    name: 'Denmark',
    dialCode: '+45',
    code: 'DK',
    image: 'flag-dk',
    latitude: 56,
    longitude: 10,
    id: 56,
  },
  {
    name: 'Djibouti',
    dialCode: '+253',
    code: 'DJ',
    image: 'flag-dj',
    latitude: 11.5,
    longitude: 43,
    id: 55,
  },
  {
    name: 'Dominica',
    dialCode: '+1 767',
    code: 'DM',
    image: 'flag-dm',
    latitude: 15.4167,
    longitude: -61.3333,
    id: 57,
  },
  {
    name: 'Dominican Republic',
    dialCode: '+1 849',
    code: 'DO',
    image: 'flag-do',
    latitude: 19,
    longitude: -70.6667,
    id: 58,
  },
  {
    name: 'Ecuador',
    dialCode: '+593',
    code: 'EC',
    image: 'flag-ec',
    latitude: -2,
    longitude: -77.5,
    id: 60,
  },
  {
    name: 'Egypt',
    dialCode: '+20',
    code: 'EG',
    image: 'flag-eg',
    latitude: 27,
    longitude: 30,
    id: 62,
  },
  {
    name: 'El Salvador',
    dialCode: '+503',
    code: 'SV',
    image: 'flag-sv',
    latitude: 13.8333,
    longitude: -88.9167,
    id: 193,
  },
  {
    name: 'Equatorial Guinea',
    dialCode: '+240',
    code: 'GQ',
    image: 'flag-gq',
    latitude: 2,
    longitude: 10,
    id: 81,
  },
  {
    name: 'Eritrea',
    dialCode: '+291',
    code: 'ER',
    image: 'flag-er',
    latitude: 15,
    longitude: 39,
    id: 63,
  },
  {
    name: 'Estonia',
    dialCode: '+372',
    code: 'EE',
    image: 'flag-ee',
    latitude: 59,
    longitude: 26,
    id: 61,
  },
  {
    name: 'Ethiopia',
    dialCode: '+251',
    code: 'ET',
    image: 'flag-et',
    latitude: 8,
    longitude: 38,
    id: 65,
  },
  {
    name: 'Falkland Islands (Malvinas)',
    dialCode: '+500',
    code: 'FK',
    image: 'flag-fk',
    latitude: -51.75,
    longitude: -59,
    id: 68,
  },
  {
    name: 'Faroe Islands',
    dialCode: '+298',
    code: 'FO',
    image: 'flag-fo',
    latitude: 62,
    longitude: -7,
    id: 70,
  },
  {
    name: 'Fiji',
    dialCode: '+679',
    code: 'FJ',
    image: 'flag-fj',
    latitude: -18,
    longitude: 175,
    id: 67,
  },
  {
    name: 'Finland',
    dialCode: '+358',
    code: 'FI',
    image: 'flag-fi',
    latitude: 64,
    longitude: 26,
    id: 66,
  },
  {
    name: 'France',
    dialCode: '+33',
    code: 'FR',
    image: 'flag-fr',
    latitude: 46,
    longitude: 2,
    id: 71,
  },
  {
    name: 'French Guiana',
    dialCode: '+594',
    code: 'GF',
    image: 'flag-gf',
    latitude: 4,
    longitude: -53,
  },
  {
    name: 'French Polynesia',
    dialCode: '+689',
    code: 'PF',
    image: 'flag-pf',
    latitude: -15,
    longitude: -140,
    id: 162,
  },
  {
    name: 'French Southern and Antarctic Lands',
    dialCode: '+262',
    code: 'TF',
    image: 'flag-tf',
    latitude: -43,
    longitude: 67,
  },
  {
    name: 'Gabon',
    dialCode: '+241',
    code: 'GA',
    image: 'flag-ga',
    latitude: -1,
    longitude: 11.75,
    id: 72,
  },
  {
    name: 'Gambia',
    dialCode: '+220',
    code: 'GM',
    image: 'flag-gm',
    latitude: 13.4667,
    longitude: -16.5667,
    id: 79,
  },
  {
    name: 'Georgia',
    dialCode: '+995',
    code: 'GE',
    image: 'flag-ge',
    latitude: 42,
    longitude: 43.5,
    id: 75,
  },
  {
    name: 'Germany',
    dialCode: '+49',
    code: 'DE',
    image: 'flag-de',
    latitude: 51,
    longitude: 9,
    id: 54,
  },
  {
    name: 'Ghana',
    dialCode: '+233',
    code: 'GH',
    image: 'flag-gh',
    latitude: 8,
    longitude: -2,
    id: 76,
  },
  {
    name: 'Gibraltar',
    dialCode: '+350',
    code: 'GI',
    image: 'flag-gi',
    latitude: 36.1833,
    longitude: -5.3667,
    id: 77,
  },
  {
    name: 'Greece',
    dialCode: '+30',
    code: 'GR',
    image: 'flag-gr',
    latitude: 39,
    longitude: 22,
    id: 82,
  },
  {
    name: 'Greenland',
    dialCode: '+299',
    code: 'GL',
    image: 'flag-gl',
    latitude: 72,
    longitude: -40,
    id: 78,
  },
  {
    name: 'Grenada',
    dialCode: '+1 473',
    code: 'GD',
    image: 'flag-gd',
    latitude: 12.1167,
    longitude: -61.6667,
    id: 74,
  },
  {
    name: 'Guadeloupe',
    dialCode: '+590',
    code: 'GP',
    image: 'flag-gp',
    latitude: 16.25,
    longitude: -61.5833,
  },
  {
    name: 'Guam',
    dialCode: '+1 671',
    code: 'GU',
    image: 'flag-gu',
    latitude: 13.4667,
    longitude: 144.7833,
    id: 84,
  },
  {
    name: 'Guatemala',
    dialCode: '+502',
    code: 'GT',
    image: 'flag-gt',
    latitude: 15.5,
    longitude: -90.25,
    id: 83,
  },
  {
    name: 'Guernsey',
    dialCode: '+44',
    code: 'GG',
    image: 'flag-gg',
    latitude: 49.5,
    longitude: -2.56,
  },
  {
    name: 'Guinea',
    dialCode: '+224',
    code: 'GN',
    image: 'flag-gn',
    latitude: 11,
    longitude: -10,
    id: 80,
  },
  {
    name: 'Guinea-Bissau',
    dialCode: '+245',
    code: 'GW',
    image: 'flag-gw',
    latitude: 12,
    longitude: -15,
    id: 85,
  },
  {
    name: 'Guyana',
    dialCode: '+592',
    code: 'GY',
    image: 'flag-gy',
    latitude: 5,
    longitude: -59,
    id: 86,
  },
  {
    name: 'Haiti',
    dialCode: '+509',
    code: 'HT',
    image: 'flag-ht',
    latitude: 19,
    longitude: -72.4167,
    id: 90,
  },
  {
    name: 'Heard Island and McDonald Islands',
    dialCode: '+672',
    code: 'HM',
    image: 'flag-hm',
    latitude: -53.1,
    longitude: 72.5167,
  },
  {
    name: 'Holy See (Vatican City State)',
    dialCode: '+379',
    code: 'VA',
    image: 'flag-va',
    latitude: 41.9,
    longitude: 12.45,
    id: 216,
  },
  {
    name: 'Honduras',
    dialCode: '+504',
    code: 'HN',
    image: 'flag-hn',
    latitude: 15,
    longitude: -86.5,
    id: 88,
  },
  {
    name: 'Hong Kong',
    dialCode: '+852',
    code: 'HK',
    image: 'flag-hk',
    latitude: 22.25,
    longitude: 114.1667,
    id: 87,
  },
  {
    name: 'Hungary',
    dialCode: '+36',
    code: 'HU',
    image: 'flag-hu',
    latitude: 47,
    longitude: 20,
    id: 91,
  },
  {
    name: 'Iceland',
    dialCode: '+354',
    code: 'IS',
    image: 'flag-is',
    latitude: 65,
    longitude: -18,
    id: 99,
  },
  {
    name: 'India',
    dialCode: '+91',
    code: 'IN',
    image: 'flag-in',
    latitude: 20,
    longitude: 77,
    id: 96,
  },
  {
    name: 'Indonesia',
    dialCode: '+62',
    code: 'ID',
    image: 'flag-id',
    latitude: -5,
    longitude: 120,
    id: 92,
  },
  {
    name: 'Iran, Islamic Republic of',
    dialCode: '+98',
    code: 'IR',
    image: 'flag-ir',
    latitude: 32,
    longitude: 53,
    id: 98,
  },
  {
    name: 'Iraq',
    dialCode: '+964',
    code: 'IQ',
    image: 'flag-iq',
    latitude: 33,
    longitude: 44,
    id: 97,
  },
  {
    name: 'Ireland',
    dialCode: '+353',
    code: 'IE',
    image: 'flag-ie',
    latitude: 53,
    longitude: -8,
    id: 93,
  },
  {
    name: 'Isle of Man',
    dialCode: '+44',
    code: 'IM',
    image: 'flag-im',
    latitude: 54.23,
    longitude: -4.55,
    id: 95,
  },
  {
    name: 'Israel',
    dialCode: '+972',
    code: 'IL',
    image: 'flag-il',
    latitude: 31.5,
    longitude: 34.75,
    id: 94,
  },
  {
    name: 'Italy',
    dialCode: '+39',
    code: 'IT',
    image: 'flag-it',
    latitude: 42.8333,
    longitude: 12.8333,
    id: 100,
  },
  {
    name: 'Jamaica',
    dialCode: '+1 876',
    code: 'JM',
    image: 'flag-jm',
    latitude: 18.25,
    longitude: -77.5,
    id: 101,
  },
  {
    name: 'Japan',
    dialCode: '+81',
    code: 'JP',
    image: 'flag-jp',
    latitude: 36,
    longitude: 138,
    id: 103,
  },
  {
    name: 'Jersey',
    dialCode: '+44',
    code: 'JE',
    image: 'flag-je',
    latitude: 49.21,
    longitude: -2.13,
  },
  {
    name: 'Jordan',
    dialCode: '+962',
    code: 'JO',
    image: 'flag-jo',
    latitude: 31,
    longitude: 36,
    id: 102,
  },
  {
    name: 'Kazakhstan',
    dialCode: '+7',
    code: 'KZ',
    image: 'flag-kz',
    latitude: 48,
    longitude: 68,
    id: 114,
  },
  {
    name: 'Kenya',
    dialCode: '+254',
    code: 'KE',
    image: 'flag-ke',
    latitude: 1,
    longitude: 38,
    id: 104,
  },
  {
    name: 'Kiribati',
    dialCode: '+686',
    code: 'KI',
    image: 'flag-ki',
    latitude: 1.4167,
    longitude: 173,
    id: 107,
  },
  {
    name: "Korea, Democratic People's Republic of",
    dialCode: '+850',
    code: 'KP',
    image: 'flag-kp',
    latitude: 40,
    longitude: 127,
    id: 110,
  },
  {
    name: 'Korea, Republic of',
    dialCode: '+82',
    code: 'KR',
    image: 'flag-kr',
    latitude: 37,
    longitude: 127.5,
    id: 111,
  },
  {
    name: 'Kuwait',
    dialCode: '+965',
    code: 'KW',
    image: 'flag-kw',
    latitude: 29.3375,
    longitude: 47.6581,
    id: 112,
  },
  {
    name: 'Kyrgyzstan',
    dialCode: '+996',
    code: 'KG',
    image: 'flag-kg',
    latitude: 41,
    longitude: 75,
    id: 105,
  },
  {
    name: "Lao People's Democratic Republic",
    dialCode: '+856',
    code: 'LA',
    image: 'flag-la',
    latitude: 18,
    longitude: 105,
    id: 115,
  },
  {
    name: 'Latvia',
    dialCode: '+371',
    code: 'LV',
    image: 'flag-lv',
    latitude: 57,
    longitude: 25,
    id: 124,
  },
  {
    name: 'Lebanon',
    dialCode: '+961',
    code: 'LB',
    image: 'flag-lb',
    latitude: 33.8333,
    longitude: 35.8333,
    id: 116,
  },
  {
    name: 'Lesotho',
    dialCode: '+266',
    code: 'LS',
    image: 'flag-ls',
    latitude: -29.5,
    longitude: 28.5,
    id: 121,
  },
  {
    name: 'Liberia',
    dialCode: '+231',
    code: 'LR',
    image: 'flag-lr',
    latitude: 6.5,
    longitude: -9.5,
    id: 120,
  },
  {
    name: 'Libyan Arab Jamahiriya',
    dialCode: '+218',
    code: 'LY',
    image: 'flag-ly',
    latitude: 25,
    longitude: 17,
    id: 125,
  },
  {
    name: 'Liechtenstein',
    dialCode: '+423',
    code: 'LI',
    image: 'flag-li',
    latitude: 47.1667,
    longitude: 9.5333,
    id: 118,
  },
  {
    name: 'Lithuania',
    dialCode: '+370',
    code: 'LT',
    image: 'flag-lt',
    latitude: 56,
    longitude: 24,
    id: 122,
  },
  {
    name: 'Luxembourg',
    dialCode: '+352',
    code: 'LU',
    image: 'flag-lu',
    latitude: 49.75,
    longitude: 6.1667,
    id: 123,
  },
  {
    name: 'Macao',
    dialCode: '+853',
    code: 'MO',
    image: 'flag-mo',
    latitude: 22.1667,
    longitude: 113.55,
    id: 137,
  },
  {
    name: 'Macedonia, The Former Yugoslav Republic of',
    dialCode: '+389',
    code: 'MK',
    image: 'flag-mk',
    latitude: 41.8333,
    longitude: 22,
    id: 133,
  },
  {
    name: 'Madagascar',
    dialCode: '+261',
    code: 'MG',
    image: 'flag-mg',
    latitude: -20,
    longitude: 47,
    id: 131,
  },
  {
    name: 'Malawi',
    dialCode: '+265',
    code: 'MW',
    image: 'flag-mw',
    latitude: -13.5,
    longitude: 34,
    id: 144,
  },
  {
    name: 'Malaysia',
    dialCode: '+60',
    code: 'MY',
    image: 'flag-my',
    latitude: 2.5,
    longitude: 112.5,
    id: 146,
  },
  {
    name: 'Maldives',
    dialCode: '+960',
    code: 'MV',
    image: 'flag-mv',
    latitude: 3.25,
    longitude: 73,
    id: 143,
  },
  {
    name: 'Mali',
    dialCode: '+223',
    code: 'ML',
    image: 'flag-ml',
    latitude: 17,
    longitude: -4,
    id: 134,
  },
  {
    name: 'Malta',
    dialCode: '+356',
    code: 'MT',
    image: 'flag-mt',
    latitude: 35.8333,
    longitude: 14.5833,
    id: 141,
  },
  {
    name: 'Marshall Islands',
    dialCode: '+692',
    code: 'MH',
    image: 'flag-mh',
    latitude: 9,
    longitude: 168,
    id: 132,
  },
  {
    name: 'Martinique',
    dialCode: '+596',
    code: 'MQ',
    image: 'flag-mq',
    latitude: 14.6667,
    longitude: -61,
  },
  {
    name: 'Mauritania',
    dialCode: '+222',
    code: 'MR',
    image: 'flag-mr',
    latitude: 20,
    longitude: -12,
    id: 139,
  },
  {
    name: 'Mauritius',
    dialCode: '+230',
    code: 'MU',
    image: 'flag-mu',
    latitude: -20.2833,
    longitude: 57.55,
    id: 142,
  },
  {
    name: 'Mayotte',
    dialCode: '+262',
    code: 'YT',
    image: 'flag-yt',
    latitude: -12.8333,
    longitude: 45.1667,
    id: 227,
  },
  {
    name: 'Mexico',
    dialCode: '+52',
    code: 'MX',
    image: 'flag-mx',
    latitude: 23,
    longitude: -102,
    id: 145,
  },
  {
    name: 'Micronesia, Federated States of',
    dialCode: '+691',
    code: 'FM',
    image: 'flag-fm',
    latitude: 6.9167,
    longitude: 158.25,
    id: 69,
  },
  {
    name: 'Moldova, Republic of',
    dialCode: '+373',
    code: 'MD',
    image: 'flag-md',
    latitude: 47,
    longitude: 29,
    id: 128,
  },
  {
    name: 'Monaco',
    dialCode: '+377',
    code: 'MC',
    image: 'flag-mc',
    latitude: 43.7333,
    longitude: 7.4,
    id: 127,
  },
  {
    name: 'Mongolia',
    dialCode: '+976',
    code: 'MN',
    image: 'flag-mn',
    latitude: 46,
    longitude: 105,
    id: 136,
  },
  {
    name: 'Montenegro',
    dialCode: '+382',
    code: 'ME',
    image: 'flag-me',
    latitude: 42,
    longitude: 19,
    id: 129,
  },
  {
    name: 'Montserrat',
    dialCode: '+1664',
    code: 'MS',
    image: 'flag-ms',
    latitude: 16.75,
    longitude: -62.2,
    id: 140,
  },
  {
    name: 'Morocco',
    dialCode: '+212',
    code: 'MA',
    image: 'flag-ma',
    latitude: 32,
    longitude: -5,
    id: 126,
  },
  {
    name: 'Mozambique',
    dialCode: '+258',
    code: 'MZ',
    image: 'flag-mz',
    latitude: -18.25,
    longitude: 35,
    id: 147,
  },
  {
    name: 'Myanmar',
    dialCode: '+95',
    code: 'MM',
    image: 'flag-mm',
    latitude: 22,
    longitude: 98,
    id: 135,
  },
  {
    name: 'Namibia',
    dialCode: '+264',
    code: 'NA',
    image: 'flag-na',
    latitude: -22,
    longitude: 17,
    id: 148,
  },
  {
    name: 'Nauru',
    dialCode: '+674',
    code: 'NR',
    image: 'flag-nr',
    latitude: -0.5333,
    longitude: 166.9167,
    id: 156,
  },
  {
    name: 'Nepal',
    dialCode: '+977',
    code: 'NP',
    image: 'flag-np',
    latitude: 28,
    longitude: 84,
    id: 155,
  },
  {
    name: 'Netherlands',
    dialCode: '+31',
    code: 'NL',
    image: 'flag-nl',
    latitude: 52.5,
    longitude: 5.75,
    id: 153,
  },
  {
    name: 'Netherlands Antilles',
    dialCode: '+599',
    code: 'AN',
    image: 'flag-an',
    latitude: 12.25,
    longitude: -68.75,
    id: 8,
  },
  {
    name: 'New Caledonia',
    dialCode: '+687',
    code: 'NC',
    image: 'flag-nc',
    latitude: -21.5,
    longitude: 165.5,
    id: 149,
  },
  {
    name: 'New Zealand',
    dialCode: '+64',
    code: 'NZ',
    image: 'flag-nz',
    latitude: -41,
    longitude: 174,
    id: 158,
  },
  {
    name: 'Nicaragua',
    dialCode: '+505',
    code: 'NI',
    image: 'flag-ni',
    latitude: 13,
    longitude: -85,
    id: 152,
  },
  {
    name: 'Niger',
    dialCode: '+227',
    code: 'NE',
    image: 'flag-ne',
    latitude: 16,
    longitude: 8,
    id: 150,
  },
  {
    name: 'Nigeria',
    dialCode: '+234',
    code: 'NG',
    image: 'flag-ng',
    latitude: 10,
    longitude: 8,
    id: 151,
  },
  {
    name: 'Niue',
    dialCode: '+683',
    code: 'NU',
    image: 'flag-nu',
    latitude: -19.0333,
    longitude: -169.8667,
    id: 157,
  },
  {
    name: 'Norfolk Island',
    dialCode: '+672',
    code: 'NF',
    image: 'flag-nf',
    latitude: -29.0333,
    longitude: 167.95,
  },
  {
    name: 'Northern Mariana Islands',
    dialCode: '+1 670',
    code: 'MP',
    image: 'flag-mp',
    latitude: 15.2,
    longitude: 145.75,
    id: 138,
  },
  {
    name: 'Norway',
    dialCode: '+47',
    code: 'NO',
    image: 'flag-no',
    latitude: 62,
    longitude: 10,
    id: 154,
  },
  {
    name: 'Oman',
    dialCode: '+968',
    code: 'OM',
    image: 'flag-om',
    latitude: 21,
    longitude: 57,
    id: 159,
  },
  {
    name: 'Pakistan',
    dialCode: '+92',
    code: 'PK',
    image: 'flag-pk',
    latitude: 30,
    longitude: 70,
    id: 165,
  },
  {
    name: 'Palau',
    dialCode: '+680',
    code: 'PW',
    image: 'flag-pw',
    latitude: 7.5,
    longitude: 134.5,
    id: 171,
  },
  {
    name: 'Palestinian Territory, Occupied',
    dialCode: '+970',
    code: 'PS',
    image: 'flag-ps',
    latitude: 32,
    longitude: 35.25,
  },
  {
    name: 'Panama',
    dialCode: '+507',
    code: 'PA',
    image: 'flag-pa',
    latitude: 9,
    longitude: -80,
    id: 160,
  },
  {
    name: 'Papua New Guinea',
    dialCode: '+675',
    code: 'PG',
    image: 'flag-pg',
    latitude: -6,
    longitude: 147,
    id: 163,
  },
  {
    name: 'Paraguay',
    dialCode: '+595',
    code: 'PY',
    image: 'flag-py',
    latitude: -23,
    longitude: -58,
    id: 172,
  },
  {
    name: 'Peru',
    dialCode: '+51',
    code: 'PE',
    image: 'flag-pe',
    latitude: -10,
    longitude: -76,
    id: 161,
  },
  {
    name: 'Philippines',
    dialCode: '+63',
    code: 'PH',
    image: 'flag-ph',
    latitude: 13,
    longitude: 122,
    id: 164,
  },
  {
    name: 'Pitcairn',
    dialCode: '+870',
    code: 'PN',
    image: 'flag-pn',
    latitude: -24.7,
    longitude: -127.4,
    id: 168,
  },
  {
    name: 'Poland',
    dialCode: '+48',
    code: 'PL',
    image: 'flag-pl',
    latitude: 52,
    longitude: 20,
    id: 166,
  },
  {
    name: 'Portugal',
    dialCode: '+351',
    code: 'PT',
    image: 'flag-pt',
    latitude: 39.5,
    longitude: -8,
    id: 170,
  },
  {
    name: 'Puerto Rico',
    dialCode: '+1 939',
    code: 'PR',
    image: 'flag-pr',
    latitude: 18.25,
    longitude: -66.5,
    id: 169,
  },
  {
    name: 'Qatar',
    dialCode: '+974',
    code: 'QA',
    image: 'flag-qa',
    latitude: 25.5,
    longitude: 51.25,
    id: 173,
  },
  {
    name: 'Réunion',
    dialCode: '+262',
    code: 'RE',
    image: 'flag-re',
    latitude: -21.1,
    longitude: 55.6,
  },
  {
    name: 'Romania',
    dialCode: '+40',
    code: 'RO',
    image: 'flag-ro',
    latitude: 46,
    longitude: 25,
    id: 174,
  },
  {
    name: 'Russia',
    dialCode: '+7',
    code: 'RU',
    image: 'flag-ru',
    latitude: 60,
    longitude: 100,
    id: 176,
  },
  {
    name: 'Rwanda',
    dialCode: '+250',
    code: 'RW',
    image: 'flag-rw',
    latitude: -2,
    longitude: 30,
    id: 177,
  },
  {
    name: 'Saint Helena, Ascension and Tristan Da Cunha',
    dialCode: '+290',
    code: 'SH',
    image: 'flag-sh',
    latitude: -15.9333,
    longitude: -5.7,
    id: 184,
  },
  {
    name: 'Saint Kitts and Nevis',
    dialCode: '+1 869',
    code: 'KN',
    image: 'flag-kn',
    latitude: 17.3333,
    longitude: -62.75,
    id: 109,
  },
  {
    name: 'Saint Lucia',
    dialCode: '+1 758',
    code: 'LC',
    image: 'flag-lc',
    latitude: 13.8833,
    longitude: -61.1333,
    id: 117,
  },
  {
    name: 'Saint Pierre and Miquelon',
    dialCode: '+508',
    code: 'PM',
    image: 'flag-pm',
    latitude: 46.8333,
    longitude: -56.3333,
    id: 167,
  },
  {
    name: 'Saint Vincent and the Grenadines',
    dialCode: '+1 784',
    code: 'VC',
    image: 'flag-vc',
    latitude: 13.25,
    longitude: -61.2,
    id: 217,
  },
  {
    name: 'Samoa',
    dialCode: '+685',
    code: 'WS',
    image: 'flag-ws',
    latitude: -13.5833,
    longitude: -172.3333,
    id: 224,
  },
  {
    name: 'San Marino',
    dialCode: '+378',
    code: 'SM',
    image: 'flag-sm',
    latitude: 43.7667,
    longitude: 12.4167,
    id: 188,
  },
  {
    name: 'Sao Tome and Principe',
    dialCode: '+239',
    code: 'ST',
    image: 'flag-st',
    latitude: 1,
    longitude: 7,
    id: 192,
  },
  {
    name: 'Saudi Arabia',
    dialCode: '+966',
    code: 'SA',
    image: 'flag-sa',
    latitude: 25,
    longitude: 45,
    id: 178,
  },
  {
    name: 'Senegal',
    dialCode: '+221',
    code: 'SN',
    image: 'flag-sn',
    latitude: 14,
    longitude: -14,
    id: 189,
  },
  {
    name: 'Serbia',
    dialCode: '+381',
    code: 'RS',
    image: 'flag-rs',
    latitude: 44,
    longitude: 21,
    id: 175,
  },
  {
    name: 'Seychelles',
    dialCode: '+248',
    code: 'SC',
    image: 'flag-sc',
    latitude: -4.5833,
    longitude: 55.6667,
    id: 180,
  },
  {
    name: 'Sierra Leone',
    dialCode: '+232',
    code: 'SL',
    image: 'flag-sl',
    latitude: 8.5,
    longitude: -11.5,
    id: 187,
  },
  {
    name: 'Singapore',
    dialCode: '+65',
    code: 'SG',
    image: 'flag-sg',
    latitude: 1.3667,
    longitude: 103.8,
    id: 183,
  },
  {
    name: 'Slovakia',
    dialCode: '+421',
    code: 'SK',
    image: 'flag-sk',
    latitude: 48.6667,
    longitude: 19.5,
    id: 186,
  },
  {
    name: 'Slovenia',
    dialCode: '+386',
    code: 'SI',
    image: 'flag-si',
    latitude: 46,
    longitude: 15,
    id: 185,
  },
  {
    name: 'Solomon Islands',
    dialCode: '+677',
    code: 'SB',
    image: 'flag-sb',
    latitude: -8,
    longitude: 159,
    id: 179,
  },
  {
    name: 'Somalia',
    dialCode: '+252',
    code: 'SO',
    image: 'flag-so',
    latitude: 10,
    longitude: 49,
    id: 190,
  },
  {
    name: 'South Africa',
    dialCode: '+27',
    code: 'ZA',
    image: 'flag-za',
    latitude: -29,
    longitude: 24,
    id: 228,
  },
  {
    name: 'South Georgia and the South Sandwich Islands',
    dialCode: '+500',
    code: 'GS',
    image: 'flag-gs',
    latitude: -54.5,
    longitude: -37,
  },
  {
    name: 'Spain',
    dialCode: '+34',
    code: 'ES',
    image: 'flag-es',
    latitude: 40,
    longitude: -4,
    id: 64,
  },
  {
    name: 'Sri Lanka',
    dialCode: '+94',
    code: 'LK',
    image: 'flag-lk',
    latitude: 7,
    longitude: 81,
    id: 119,
  },
  {
    name: 'Sudan',
    dialCode: '+249',
    code: 'SD',
    image: 'flag-sd',
    latitude: 15,
    longitude: 30,
    id: 181,
  },
  {
    name: 'Suriname',
    dialCode: '+597',
    code: 'SR',
    image: 'flag-sr',
    latitude: 4,
    longitude: -56,
    id: 191,
  },
  {
    name: 'Svalbard and Jan Mayen',
    dialCode: '+47',
    code: 'SJ',
    image: 'flag-sj',
    latitude: 78,
    longitude: 20,
  },
  {
    name: 'Swaziland',
    dialCode: '+268',
    code: 'SZ',
    image: 'flag-sz',
    latitude: -26.5,
    longitude: 31.5,
    id: 195,
  },
  {
    name: 'Sweden',
    dialCode: '+46',
    code: 'SE',
    image: 'flag-se',
    latitude: 62,
    longitude: 15,
    id: 182,
  },
  {
    name: 'Switzerland',
    dialCode: '+41',
    code: 'CH',
    image: 'flag-ch',
    latitude: 47,
    longitude: 8,
    id: 41,
  },
  {
    name: 'Syrian Arab Republic',
    dialCode: '+963',
    code: 'SY',
    image: 'flag-sy',
    latitude: 35,
    longitude: 38,
    id: 194,
  },
  {
    name: 'Taiwan',
    dialCode: '+886',
    code: 'TW',
    image: 'flag-tw',
    latitude: 23.5,
    longitude: 121,
    id: 209,
  },
  {
    name: 'Tajikistan',
    dialCode: '+992',
    code: 'TJ',
    image: 'flag-tj',
    latitude: 39,
    longitude: 71,
    id: 200,
  },
  {
    name: 'Tanzania, United Republic of',
    dialCode: '+255',
    code: 'TZ',
    image: 'flag-tz',
    latitude: -6,
    longitude: 35,
    id: 210,
  },
  {
    name: 'Thailand',
    dialCode: '+66',
    code: 'TH',
    image: 'flag-th',
    latitude: 15,
    longitude: 100,
    id: 199,
  },
  {
    name: 'Timor-Leste',
    dialCode: '+670',
    code: 'TL',
    image: 'flag-tl',
    latitude: -8.55,
    longitude: 125.5167,
    id: 202,
  },
  {
    name: 'Togo',
    dialCode: '+228',
    code: 'TG',
    image: 'flag-tg',
    latitude: 8,
    longitude: 1.1667,
    id: 198,
  },
  {
    name: 'Tokelau',
    dialCode: '+690',
    code: 'TK',
    image: 'flag-tk',
    latitude: -9,
    longitude: -172,
    id: 201,
  },
  {
    name: 'Tonga',
    dialCode: '+676',
    code: 'TO',
    image: 'flag-to',
    latitude: -20,
    longitude: -175,
    id: 205,
  },
  {
    name: 'Trinidad and Tobago',
    dialCode: '+1 868',
    code: 'TT',
    image: 'flag-tt',
    latitude: 11,
    longitude: -61,
    id: 207,
  },
  {
    name: 'Tunisia',
    dialCode: '+216',
    code: 'TN',
    image: 'flag-tn',
    latitude: 34,
    longitude: 9,
    id: 204,
  },
  {
    name: 'Turkey',
    dialCode: '+90',
    code: 'TR',
    image: 'flag-tr',
    latitude: 39,
    longitude: 35,
    id: 206,
  },
  {
    name: 'Turkmenistan',
    dialCode: '+993',
    code: 'TM',
    image: 'flag-tm',
    latitude: 40,
    longitude: 60,
    id: 203,
  },
  {
    name: 'Turks and Caicos Islands',
    dialCode: '+1 649',
    code: 'TC',
    image: 'flag-tc',
    latitude: 21.75,
    longitude: -71.5833,
    id: 196,
  },
  {
    name: 'Tuvalu',
    dialCode: '+688',
    code: 'TV',
    image: 'flag-tv',
    latitude: -8,
    longitude: 178,
    id: 208,
  },
  {
    name: 'Uganda',
    dialCode: '+256',
    code: 'UG',
    image: 'flag-ug',
    latitude: 1,
    longitude: 32,
    id: 212,
  },
  {
    name: 'Ukraine',
    dialCode: '+380',
    code: 'UA',
    image: 'flag-ua',
    latitude: 49,
    longitude: 32,
    id: 211,
  },
  {
    name: 'United Arab Emirates',
    dialCode: '+971',
    code: 'AE',
    image: 'flag-ae',
    latitude: 24,
    longitude: 54,
    id: 2,
  },
  {
    name: 'United Kingdom',
    dialCode: '+44',
    code: 'GB',
    image: 'flag-gb',
    latitude: 54,
    longitude: -2,
    id: 73,
  },
  {
    name: 'United States',
    dialCode: '+1',
    code: 'US',
    image: 'flag-us',
    latitude: 38,
    longitude: -97,
    id: 213,
  },
  {
    name: 'United States Minor Outlying Islands',
    dialCode: '+1581',
    code: 'UM',
    image: 'flag-um',
    latitude: 19.2833,
    longitude: 166.6,
  },
  {
    name: 'Uruguay',
    dialCode: '+598',
    code: 'UY',
    image: 'flag-uy',
    latitude: -33,
    longitude: -56,
    id: 214,
  },
  {
    name: 'Uzbekistan',
    dialCode: '+998',
    code: 'UZ',
    image: 'flag-uz',
    latitude: 41,
    longitude: 64,
    id: 215,
  },
  {
    name: 'Vanuatu',
    dialCode: '+678',
    code: 'VU',
    image: 'flag-vu',
    latitude: -16,
    longitude: 167,
    id: 222,
  },
  {
    name: 'Venezuela, Bolivarian Republic of',
    dialCode: '+58',
    code: 'VE',
    image: 'flag-ve',
    latitude: 8,
    longitude: -66,
    id: 218,
  },
  {
    name: 'Viet Nam',
    dialCode: '+84',
    code: 'VN',
    image: 'flag-vn',
    latitude: 16,
    longitude: 106,
    id: 221,
  },
  {
    name: 'Virgin Islands, British',
    dialCode: '+1 284',
    code: 'VG',
    image: 'flag-vg',
    latitude: 18.5,
    longitude: -64.5,
    id: 219,
  },
  {
    name: 'Virgin Islands, U.S.',
    dialCode: '+1 340',
    code: 'VI',
    image: 'flag-vi',
    latitude: 18.3333,
    longitude: -64.8333,
    id: 220,
  },
  {
    name: 'Wallis and Futuna',
    dialCode: '+681',
    code: 'WF',
    image: 'flag-wf',
    latitude: -13.3,
    longitude: -176.2,
    id: 223,
  },
  {
    name: 'Western Sahara',
    dialCode: '+732',
    code: 'EH',
    image: 'flag-eh',
    latitude: 24.5,
    longitude: -13,
  },
  {
    name: 'Yemen',
    dialCode: '+967',
    code: 'YE',
    image: 'flag-ye',
    latitude: 15,
    longitude: 48,
    id: 226,
  },
  {
    name: 'Zambia',
    dialCode: '+260',
    code: 'ZM',
    image: 'flag-zm',
    latitude: -15,
    longitude: 30,
    id: 229,
  },
  {
    name: 'Zimbabwe',
    dialCode: '+263',
    code: 'ZW',
    image: 'flag-zw',
    latitude: -20,
    longitude: 30,
    id: 230,
  },
];
